### ISSUE TITLE
The application doesn't respect the username specified in the chart values

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/plugin-health-scoring#43]
From the pod logs:

> org.postgresql.util.PSQLException: FATAL: password authentication failed for user "plugin-health-scoring" 

Release values in [the corresponding secret](https://github.com/jenkins-infra/charts-secrets/blob/main/config/plugin-health-scoring/secrets.yaml) (sops encrypted file, in a private repo):
```yaml
database:
    username: plugin_health
    password: XXXXXXXXXXXXXXX
    server: public.postgres.database.azure.com
    name: plugin_health
```
Secret passed as values of the chart: https://github.com/jenkins-infra/kubernetes-management/blob/4da71ea7204cb1f862f304c4981c7a8b447370d6/clusters/prodpublick8s.yaml#L287

# Expected result:
The app use the values specified via the chart.

Suggestion: retrieve the `username` (and all other parameters) from the environment variable `POSTGRE_USER`: https://github.com/jenkins-infra/helm-charts/blob/b7e23c32ddfb15e620aa3428ad61847f183dd719/charts/plugin-health-scoring/templates/deployment.yaml#L57

Related to: https://github.com/jenkins-infra/helpdesk/issues/3114
